nacos:
  address: 1.117.70.65:8848
  username: nacos
  password: nacos_start!!!

spring:
  main:
    allow-circular-references: true
  application:
    name: seckill-service


  cloud:
    nacos:
      config:
        server-addr: ${nacos.address}
        username: ${nacos.username}
        password: ${nacos.password}
        file-extension: yaml
        refresh-enabled: true
        namespace: shop-flashsale
        shared-configs:
          - data-id: redis-config-dev.yaml
          - data-id: rocketmq-config-dev.yaml

      discovery:
        server-addr: ${nacos.address}
        username: ${nacos.username}
        password: ${nacos.password}


  config:
    import:
      - optional:nacos:seckill-service-dev.yaml
      - optional:nacos:redis-config-dev.yaml
      - optional:nacos:rocketmq-config-dev.yaml


rocketmq:
  producer:
    group: ORDER_PENDING_PRODUCER_GROUP